// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxah68i0POd_ExOZcWMdnK-9WJ2dTJW_A',
    appId: '1:752703653543:web:cb8f09665cdda81a5bbd82',
    messagingSenderId: '752703653543',
    projectId: 'aihub-790af',
    authDomain: 'aihub-790af.firebaseapp.com',
    storageBucket: 'aihub-790af.firebasestorage.app',
    measurementId: 'G-FPK1SCGS03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_WfN2BaTATZnXpxiVjZqpX_QEOZNna3o',
    appId: '1:752703653543:android:6e7df3cdc676f1485bbd82',
    messagingSenderId: '752703653543',
    projectId: 'aihub-790af',
    storageBucket: 'aihub-790af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmWLa8dXgmvXzldUg0wU0k3ro0xLTw5tg',
    appId: '1:752703653543:ios:c9257b249b9f59495bbd82',
    messagingSenderId: '752703653543',
    projectId: 'aihub-790af',
    storageBucket: 'aihub-790af.firebasestorage.app',
    iosBundleId: 'com.example.aiHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmWLa8dXgmvXzldUg0wU0k3ro0xLTw5tg',
    appId: '1:752703653543:ios:c9257b249b9f59495bbd82',
    messagingSenderId: '752703653543',
    projectId: 'aihub-790af',
    storageBucket: 'aihub-790af.firebasestorage.app',
    iosBundleId: 'com.example.aiHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxah68i0POd_ExOZcWMdnK-9WJ2dTJW_A',
    appId: '1:752703653543:web:94047cca6f490bf95bbd82',
    messagingSenderId: '752703653543',
    projectId: 'aihub-790af',
    authDomain: 'aihub-790af.firebaseapp.com',
    storageBucket: 'aihub-790af.firebasestorage.app',
    measurementId: 'G-EBSRWK5ZXM',
  );
}
